resolver: lts-6.4
packages:
- '.'
- location:
    git: https://github.com/kmein/ciphers
    commit: 79497eae656b6395f07b134d82e113bfa708baf7
  extra-dep: true
extra-deps: []

flags: {}

extra-package-dbs: []
