resolver: lts-6.4
packages:
- '.'
- location:
    git: https://github.com/kmein/ciphers
    commit: de033ce3b0e9f8d9f289c93267ffada3907fad1e
  extra-dep: true
extra-deps: []

flags: {}

extra-package-dbs: []
